// sitemap-pro · core (framework-agnostic)
// Builds Yoast/RankMath-style sitemaps: a sitemap INDEX that links to per-type
// sub-sitemaps, each with hreflang alternates, lastmod, optional images, and an
// optional XSL stylesheet reference for a human-friendly view. Pure strings, no
// dependencies — usable from Astro endpoints, Next route handlers, or any build.

export type ChangeFreq =
  | "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";

/** hreflang alternate for an i18n URL (e.g. { hreflang: "en", href: "https://…/en/…" }). */
export type Alternate = { hreflang: string; href: string };

/**
 * An image entry for a URL. A bare string is shorthand for `{ loc }`.
 * NOTE: Google reads only `<image:loc>` (it deprecated title/caption in 2022); the
 * extra fields stay valid per the image sitemap protocol and are used by other engines.
 */
export type ImageInfo = { loc: string; title?: string; caption?: string };

/** Google News annotation for a URL — pairs with a News sitemap (`./news`). */
export type NewsInfo = {
  /** Publication name, e.g. "EspecialMundial". */
  publicationName: string;
  /** Publication language (ISO 639, e.g. "es", "en"). */
  publicationLanguage: string;
  /** Article publication date (W3C datetime). */
  publicationDate: string | Date;
  /** Article headline (must match the on-page title). */
  title: string;
  /** Optional comma-separated (or array) keywords. */
  keywords?: string[] | string;
};

export type SitemapUrl = {
  loc: string;
  lastmod?: string | Date;
  changefreq?: ChangeFreq;
  priority?: number;
  /** hreflang alternates (multilingual sites). Include an "x-default" if you have one. */
  alternates?: Alternate[];
  /** Images to attach as <image:image>. A string is shorthand for `{ loc }`. */
  images?: (string | ImageInfo)[];
  /** Google News annotation (<news:news>). Build these with `newsUrls` from `./news`. */
  news?: NewsInfo;
};

export type SubSitemap = { loc: string; lastmod?: string | Date };

export type RenderOptions = {
  /** Href of the XSL stylesheet, or null to omit the processing instruction. Default "/sitemap.xsl". */
  stylesheetHref?: string | null;
  /** Add the generator credit comment (component + sitemaps.org). Default true. */
  credit?: boolean;
};

export const REPO_URL = "https://github.com/dcarrero/Astro-Sitemap-pro-Component";

// Yoast-style attribution: a comment in the raw XML citing the generator.
const CREDIT_COMMENT =
  `<!-- Generated by astro-sitemap-pro-component (MIT) · ${REPO_URL} · ` +
  `This is an XML Sitemap, meant for consumption by search engines. More info: https://www.sitemaps.org -->`;

function credit(opts?: RenderOptions): string {
  return opts?.credit === false ? "" : `\n${CREDIT_COMMENT}`;
}

const SITEMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9";
const XHTML_NS = "http://www.w3.org/1999/xhtml";
const IMAGE_NS = "http://www.google.com/schemas/sitemap-image/1.1";
const NEWS_NS = "http://www.google.com/schemas/sitemap-news/0.9";

export function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function iso(d: string | Date | undefined): string | undefined {
  if (d == null) return undefined;
  return typeof d === "string" ? d : d.toISOString();
}

/**
 * The most recent lastmod among items (ISO string), or undefined if none carry one.
 * Use it to derive an HONEST `<lastmod>` for a sub-sitemap in the index straight from
 * the URLs it lists — instead of hand-maintaining (and forgetting) it:
 *
 *   renderIndex([{ loc: "/news-sitemap.xml", lastmod: latestLastmod(newsUrls) }, …])
 *
 * Assumes ISO-8601/UTC timestamps, which sort lexicographically.
 */
export function latestLastmod(items: { lastmod?: string | Date }[]): string | undefined {
  let best: string | undefined;
  for (const it of items) {
    const v = iso(it.lastmod);
    if (v && (best === undefined || v > best)) best = v;
  }
  return best;
}

function stylesheetPI(opts?: RenderOptions): string {
  const href = opts?.stylesheetHref === undefined ? "/sitemap.xsl" : opts.stylesheetHref;
  return href ? `\n<?xml-stylesheet type="text/xsl" href="${escapeXml(href)}"?>` : "";
}

function imageBlock(img: string | ImageInfo): string {
  const i = typeof img === "string" ? { loc: img } : img;
  return (
    `<image:image><image:loc>${escapeXml(i.loc)}</image:loc>` +
    (i.title ? `<image:title>${escapeXml(i.title)}</image:title>` : "") +
    (i.caption ? `<image:caption>${escapeXml(i.caption)}</image:caption>` : "") +
    `</image:image>`
  );
}

function newsBlock(n: NewsInfo): string {
  const date = iso(n.publicationDate);
  const kw =
    n.keywords == null ? "" : Array.isArray(n.keywords) ? n.keywords.join(", ") : n.keywords;
  return (
    `<news:news>` +
    `<news:publication>` +
    `<news:name>${escapeXml(n.publicationName)}</news:name>` +
    `<news:language>${escapeXml(n.publicationLanguage)}</news:language>` +
    `</news:publication>` +
    (date ? `<news:publication_date>${escapeXml(date)}</news:publication_date>` : "") +
    `<news:title>${escapeXml(n.title)}</news:title>` +
    (kw ? `<news:keywords>${escapeXml(kw)}</news:keywords>` : "") +
    `</news:news>`
  );
}

/** Render a <urlset> (one sub-sitemap). */
export function renderUrlset(urls: SitemapUrl[], opts?: RenderOptions): string {
  const needsXhtml = urls.some((u) => u.alternates?.length);
  const needsImage = urls.some((u) => u.images?.length);
  const needsNews = urls.some((u) => u.news);
  const ns =
    `xmlns="${SITEMAP_NS}"` +
    (needsXhtml ? ` xmlns:xhtml="${XHTML_NS}"` : "") +
    (needsImage ? ` xmlns:image="${IMAGE_NS}"` : "") +
    (needsNews ? ` xmlns:news="${NEWS_NS}"` : "");

  const body = urls
    .map((u) => {
      const lastmod = iso(u.lastmod);
      const alts = (u.alternates ?? [])
        .map(
          (a) =>
            `<xhtml:link rel="alternate" hreflang="${escapeXml(a.hreflang)}" href="${escapeXml(a.href)}"/>`,
        )
        .join("");
      const imgs = (u.images ?? []).map(imageBlock).join("");
      const news = u.news ? newsBlock(u.news) : "";
      return (
        `<url><loc>${escapeXml(u.loc)}</loc>` +
        (lastmod ? `<lastmod>${escapeXml(lastmod)}</lastmod>` : "") +
        (u.changefreq ? `<changefreq>${u.changefreq}</changefreq>` : "") +
        (u.priority != null ? `<priority>${u.priority.toFixed(1)}</priority>` : "") +
        alts +
        news +
        imgs +
        `</url>`
      );
    })
    .join("");

  return `<?xml version="1.0" encoding="UTF-8"?>${stylesheetPI(opts)}${credit(opts)}\n<urlset ${ns}>${body}</urlset>`;
}

/** Render the <sitemapindex> that links to every sub-sitemap. */
export function renderIndex(subs: SubSitemap[], opts?: RenderOptions): string {
  const body = subs
    .map((s) => {
      const lastmod = iso(s.lastmod);
      return (
        `<sitemap><loc>${escapeXml(s.loc)}</loc>` +
        (lastmod ? `<lastmod>${escapeXml(lastmod)}</lastmod>` : "") +
        `</sitemap>`
      );
    })
    .join("");
  return `<?xml version="1.0" encoding="UTF-8"?>${stylesheetPI(opts)}${credit(opts)}\n<sitemapindex xmlns="${SITEMAP_NS}">${body}</sitemapindex>`;
}

/** Wrap an XML string in a web-standard Response (works in Astro & Next handlers). */
export function xmlResponse(xml: string): Response {
  return new Response(xml, {
    headers: { "content-type": "application/xml; charset=utf-8" },
  });
}
